# Dockerfile for React App
# Use the official Node.js image as the builder
FROM node:18 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire app source code into the working directory
COPY . .



# Expose the port Nginx will run on
EXPOSE 3000


CMD ["npm","start"]
